module.exports = {
  rules: {
    "@angular-eslint/contextual-decorator": "warn",
    "@angular-eslint/contextual-lifecycle": "warn",
    "@angular-eslint/no-attribute-decorator": "warn",
    "@angular-eslint/no-lifecycle-call": "warn",
    "@angular-eslint/no-output-native": "warn",
    "@angular-eslint/no-pipe-impure": "warn",
    "@angular-eslint/prefer-on-push-component-change-detection": "warn",
    "@angular-eslint/use-injectable-provided-in": "warn",
    "@angular-eslint/component-max-inline-declarations": "warn",
    "@angular-eslint/no-conflicting-lifecycle": "warn",
    "@angular-eslint/no-forward-ref": "warn",
    "@angular-eslint/no-input-prefix": "warn",
    "@angular-eslint/prefer-output-readonly": "warn",
    "@angular-eslint/relative-url-prefix": "warn",
    "@angular-eslint/use-component-selector": "warn",
    "@angular-eslint/use-component-view-encapsulation": "warn",
    "@angular-eslint/component-selector": "warn",
    "@angular-eslint/directive-selector": "warn",
    "@angular-eslint/no-queries-metadata-property": "warn",
    "@angular-eslint/pipe-prefix": "warn",
    "@angular-eslint/component-class-suffix": "warn",
    "@angular-eslint/directive-class-suffix": "warn",
    "@angular-eslint/no-host-metadata-property": "warn",
    "@angular-eslint/no-input-rename": "warn",
    "@angular-eslint/no-inputs-metadata-property": "warn",
    "@angular-eslint/no-output-on-prefix": "warn",
    "@angular-eslint/no-output-rename": "warn",
    "@angular-eslint/no-outputs-metadata-property": "warn",
    "@angular-eslint/use-lifecycle-interface": "warn",
    "@angular-eslint/use-pipe-transform-interface": "warn",
  },
};
